resources:
  repositories:
  - repository: configuration
    type: github
    endpoint: Doron_GitHub
    name: doronamsalem/configuration

trigger:
- dev

pool:
  name: Default

variables:
  compose_path: ~/local_agent/_work/2/s/docker-compose.yml
  major_v: 1
  minor_v: 0
  image_tag: "version" #"$(major_v).$(minor_v)."
  

steps:

- script: |
    docker system prune -a -f
  displayName: 'Clean docker environment'

- script: |
    echo sonarqube
  displayName: 'Static testing'


- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'doron_DockerHub'
    dockerComposeFile: $(compose_path)
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'push staging'

- script: |
    echo $(DOCKERHUB_PSW) | sudo docker login -u $(DOCKERHUB_USR) --password-stdin
    docker-compose -f $(compose_path) build
    docker-compose -f $(compose_path) push staging
  displayName: 'Build images & push staging'

# - script: | # should change ~/configuration/k8s to Kustomize overlay
#     kubectl apply -f ~/configuration/k8s/staging.yml
#     python3 ./unittests/website_response.py'
#     kubectl delete -f ~/configuration/k8s/staging.yml
#     docker-compose -f $(compose_path) push production
#   displayName: 'Test staging & push production'

- script: | #trigger argocd
    cd ~/configuration
    #git pull  for prevente conflict
    sed -i "14s/tag:.*/tag: $(image_tag)/g" ~/configuration/helm-production/values.yaml
    git add ~/configuration/helm-production/values.yaml
    git commit -m "new production version"
    git push
  displayName: 'Update deployment image tag'


- script: |
    docker-compose -f $(compose_path) down --remove-orphans -v
    docker system prune -a -f
    docker logout
    rm -rf ~/configuration
  displayName: 'Post clean environment'
