resources:
  repositories:
  - repository: configuration
    type: github
    endpoint: Doron_GitHub
    name: doronamsalem/configuration

trigger:
- dev

pool:
  name: Default

variables:
  compose_path: ./docker-compose.yml
  major_v: 1
  minor_v: 0
  image_tag: "version" #"$(major_v).$(minor_v)."
  

steps:

- script: |
    pwd
    echo "cd ~" 
    cd ~
    tree

    docker system prune -a -f
  displayName: 'Clean docker environment'

- script: |
    echo sonarqube
  displayName: 'Static testing'

- script: |
    docker login -u $(DOCKERHUB_USR) -p $(DOCKERHUB_PSW)
    docker-compose -f $(compose_path) build
    docker-compose -f $(compose_path) push staging
  displayName: 'Build & push images'

- script: |
    kubectl apply -f https://github.com/doronamsalem/configuration/blob/main/k8s/staging.yml
    python3 ./unittests/website_response.py'
    kubectl delete -f https://github.com/doronamsalem/configuration/blob/main/k8s/staging.yml
  displayName: 'Test the app'

- script: |
    docker-compose -f $(compose_path) push production
    git clone 
  displayName: 'Push prod image and update deployment image tag'


- script: |
    docker-compose -f $(compose_path) down --remove-orphans -v
    docker system prune -a -f
    docker logout
  displayName: 'Clean environment'
