services:
  test:
    build: .
    image: test_image:version
    restart: unless-stopped
    ports:
      - "8081:8081"
      
  production:
    build: .
    image: doronamsalem/production:version
    restart: unless-stopped
    ports:
      - "8081:8081"
