services:
  staging:
    build: .
    image: doronamsalem/staging:version
    restart: unless-stopped
    ports:
      - "8081:8081"
      
  production:
    build: .
    image: doronamsalem/production:version
    restart: unless-stopped
    ports:
      - "8081:8081"
